### ISSUE TITLE
Moving to angular

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/job-board#9]
I'm moving this to angular. We've had a lot of success with Angular with our past projects, and I think angular will help make this website more dynamic. The things we need are more front-end heavy, and I think the progress we've made with Intranet/Blueprint/Checkin will help us make the job-board dynamic as well. 

I'll start the port then we'll reconsider and see how things are.

**Comment by ethanresnick** [comment]
Sgtm. Fyi for the port, the embed code for our different typekit kits is below. This code will be listed on Frontify soon to encourage consistent use (something Cheryl asked me to do, but that I haven't yet since I don't have access; maybe @oa495 can help?). But for now, it's here:

### Meta (Normal, Normal Italic, Bold, Bold Italic)
<script src="https://use.typekit.net/bpm7cfb.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

### Meta (Normal, Normal Italic, Bold) and Freight Text (Book, Book Italic, Bold, Bold Italic, Black)
<script src="https://use.typekit.net/xko1fbx.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

### Meta (Small Caps, Normal, Bold) and Freight Text (Book, Book Italic)
<script src="https://use.typekit.net/ikp8upt.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

To date, Inconsolata hasn't been included in these kits, since we've been loading it from Google Fonts, but it'd probably be better for performance to load it from Typekit too (would save us a request + dns lookup). So I'm happy to add new kits that bake Inconsolata in or that have different weight/style combinations for the different sites.

I'm bringing these kits up here since the job board currently uses Merriweather as its serif, which isn't part of any styleguide; it should use Freight or Inconsolata instead.

**Comment by AbhiAgarwal** [comment]
@ethanresnick Thanks! Really helpful :) glad to have this documented here. I'm doing an initial code push then we can definitely start working on the design. We can start thinking about new features to add (such as filters), and how we can embed those into the design.

**Comment by ethanresnick** [comment]
:+1:
